name: 💬 GitHub Question/Problem
description: What question should I answer next?
labels: ["information", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Do you know a common I-don't-know-how-to question that is not answered in this repository? Make a suggestion.
        
        First:
        - Real quick, check that the answer can be found easily in [GitHub Docs](https://docs.github.com/).
        - This form is for suggesting that I answer a frequent question about doing something on GitHub. If you'd like to ask a question about _this repository_, go [here](https://github.com/DNin01/help-for-github-users/discussions/categories/help-and-questions).
        - Search for issues to see if anyone else mentioned your question. You can 👍 that issue if you had the same question.
        
        If you couldn't find the answer, continue.

  - type: textarea
    id: problem
    attributes:
      label: Question/Problem
      description: Provide some details about the question.
      placeholder: How do you customize X?
    validations:
      required: true
